### ISSUE TITLE
/api/v1/k8s/velero/manifest 404 not found

### ISSUE THREAD

**Issue by Llyr95** [seriohub/velero-api#45]
Hi,

I am having this issue where I get a 404 not found response when the ui uses /api/v1/k8s/velero/manifest, basically each time I try to open a velero ressource on the dashboard (a backup in the backup list for example).

Would you kindly help me troubleshoot this ?

Thanks!

<img width="444" alt="Image" src="https://github.com/user-attachments/assets/c89ac4a5-f41c-4b2f-b80c-55256c3760b6" />

<img width="1079" alt="Image" src="https://github.com/user-attachments/assets/284fac25-3b07-4287-b88d-f2e3c9b77bff" />

<img width="1495" alt="Image" src="https://github.com/user-attachments/assets/c34e18f1-8ff4-43ac-9098-daf3c90dccba" />

**Comment by davideserio** [comment]
Hi,
could you please check the logs of the velero-api pod and post any error messages that occur when the /api/v1/k8s/velero/manifest endpoint is called?

**Comment by davideserio** [comment]
A new chart version 0.1.23/app 0.1.20 has been released. This should resolve the issue.
Let us know if you encounter any further problems

**Comment by Llyr95** [comment]
I updated the chart and I can now get informations on backup, schedule etc!

However now I have an issue with the dashboard, it is not loading anymore :/

I have this error showing in the UI : `HTTP 400 Bad Request: Error: 'NoneType' object is not iterable | File: service/stats.py | Function: get_velero_stats | Line: 93`

I can't get the logs either : `HTTP 400 Bad Request: Error: 400: Error 408: Request Timeout 400: Invalid response: Content-Type application/octet-stream | File: service/logs.py | Function: get_backup_logs | Line: 38`

I also have this error when I load the page showing the information about a specific backup : 
`Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '3732ca96-d615-457c-a863-a19ba26d1dda', 'X-Kubernetes-Pf-Prioritylevel-Uid': '1f030d66-2825-422f-97b2-3a5c8633f8b3', 'Date': 'Wed, 05 Mar 2025 11:54:32 GMT', 'Content-Length': '363'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"podvolumebackups.velero.io is forbidden: User \"system:serviceaccount:velero-ui:vui-admin-sa\" cannot list resource`

Thank you for your help

**Comment by davideserio** [comment]
It looks like an RBAC issue. Which version of Kubernetes was used for the installation? 
Could you check if the service account vui-admin-sa has the vui-admin and vui-velero-admin role and the vui-cluster-readonly clusterrole assigned?

**Comment by Llyr95** [comment]
Looks like it. I am using kubernetes v1.32.2
<img width="2232" alt="Image" src="https://github.com/user-attachments/assets/e66c4c26-605f-4731-a41c-045611822d07" />

**Comment by davideserio** [comment]
Could you confirm that the images with the following tags are running?
- velero-api:0.2.0
- velero-ui:0.2.0

**Comment by Llyr95** [comment]
Yes, they are running 0.2.0

<img width="1129" alt="Image" src="https://github.com/user-attachments/assets/f7e2ca3e-06ab-42dd-a6fb-92a569216d21" />

**Comment by davideserio** [comment]
Set the following variable in Helm and let me know if it resolves the issue:
https://github.com/seriohub/velero-helm/blob/65735430c11cf9e2883be46f93d296aaa9bdf5ff/values-override.yaml#L8

**Comment by Llyr95** [comment]
I am already using global.veleroNamespace variable

**Comment by davideserio** [comment]
Can you check the value of the K8S_VELERO_NAMESPACE variable inside the API pod?

**Comment by Llyr95** [comment]
`echo $K8S_VELERO_NAMESPACE` returns the correct namespace where velero resides

**Comment by davideserio** [comment]
I have just deployed the [dev](https://hub.docker.com/r/dserio83/velero-api/tags) image, which should fix the bug related to PodVolumeBackup. Could you add the following lines to the deployment files and confirm that the issue no longer occurs?

```
api:
  apiServer:
    image:
      tag: dev
```

**Comment by Llyr95** [comment]
I have another issue that prevent the api pod from starting. Here is the log : 

```
│ api-server ERROR     [Path validation] key:VELERO_CLI_PATH                     type:path       value:                          validation:NOT VALID PATH                                               │
│ api-server ERROR     [Path validation] key:VELERO_CLI_DEST_PATH                type:path       value:                          validation:NOT VALID PATH                                               │
│ api-server ConfigHelper [Path validation] key:SECURITY_PATH_DATABASE              type:path       value:./data                    validation:OK                                                        │
│ api-server ERROR     [Path validation] key:VELERO_CLI_PATH_CUSTOM              type:path       value:                          validation:NOT VALID PATH                                               │
│ api-server ConfigHelper [Env validation ] key:API_RATE_LIMITER_L1                 type:complex    value:60:100                    validation:OK                                                        │
│ api-server ConfigHelper [Env validation ] key:API_RATE_LIMITER_CUSTOM_1           type:complex    value:60:100                    validation:OK                                                        │
│ api-server ConfigHelper ERROR [Gen validation ] Mandatory env variables set: False                                                                                                                     │
│ api-server ConfigHelper ERROR [Gen Validation ] !!!Warning:The application can not start. Try to update the keys in errors and restart the program. 
```



I did not add those variable keys before so they are not in the helm values I provide. I tried reinstalling the helm chart too, same thing.

I then tried by removing the `apiConfig.securityTokenKey` because there was an error related to this in the log. The pod started. I can still see some error related to this : 


``` 
│ api-server ConfigHelper create_env_variables                                                                                                                                                           │
│ api-server ConfigHelper create_env_variables SECURITY_TOKEN_KEY                                                                                                                                        │
│ api-server ConfigHelper key: SECURITY_TOKEN_KEY value:                          validation:ERROR NOT A VALID SECRET KEY                                                                                │
│ api-server ConfigHelper create SECURITY_TOKEN_KEY                                                                                                                                                      │
│ api-server ConfigHelper reload SECURITY_TOKEN_KEY: 62212402ae5531782d72986876af3ced81a2e84c -(62212402ae5296b291beced81a2e84c)                │
│ api-server ConfigHelper create_env_variables SECURITY_REFRESH_TOKEN_KEY                                                                                                                                │
│ api-server ConfigHelper key: SECURITY_REFRESH_TOKEN_KEY value:                          validation:ERROR NOT A VALID SECRET KEY                                                                        │
│ api-server ConfigHelper create SECURITY_REFRESH_TOKEN_KEY                                                                                                                                              │
│ api-server ConfigHelper reload SECURITY_REFRESH_TOKEN_KEY: 3d1b1766e95c4975a6646593829ebc0859c1eea495e96 -(36cd0551b84164a4e575d1b1766e95c459c1eea495e96)  
```

Now that the pod started, unfortunately the issues are not solved, I still get the error `HTTP 400 Bad Request: Error: 'NoneType' object is not iterable | File: service/stats.py | Function: get_velero_stats | Line: 93` in the dashboard, which is not loading.

I also still get the issue with the PodVolumeBackup in a backup page, the podvolume frame is empty
```
Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '3732ca96-d615-457c-a863-a19ba26d1dda', 'X-Kubernetes-Pf-Prioritylevel-Uid': '1f030d66-2825-422f-97b2-3a5c8633f8b3', 'Date': 'Thu, 06 Mar 2025 08:09:02 GMT', 'Content-Length': '363'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"podvolumebackups.velero.io is forbidden: User \"system:serviceaccount:velero-ui:vui-admin-sa\" cannot list resource
```

Some other logs I have in the api pod : 

```
│ api-server Traceback (most recent call last):                                                                                                                                                          │
│ api-server   File "/app/ws/websocket_manager.py", line 24, in connect                                                                                                                                  │
│ api-server     message = await websocket.receive_text()                                                                                                                                                │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 119, in receive_text                                                                                         │
│ api-server     self._raise_on_disconnect(message)                                                                                                                                                      │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 113, in _raise_on_disconnect                                                                                 │
│ api-server     raise WebSocketDisconnect(message["code"], message.get("reason"))                                                                                                                       │
│ api-server starlette.websockets.WebSocketDisconnect: (1005, None)                                                                                                                                      │
│ api-server Traceback (most recent call last):                                                                                                                                                          │
│ api-server   File "/app/ws/websocket_manager.py", line 24, in connect                                                                                                                                  │
│ api-server     message = await websocket.receive_text()                                                                                                                                                │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 119, in receive_text                                                                                         │
│ api-server     self._raise_on_disconnect(message)                                                                                                                                                      │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 113, in _raise_on_disconnect                                                                                 │
│ api-server     raise WebSocketDisconnect(message["code"], message.get("reason"))                                                                                                                       │
│ api-server starlette.websockets.WebSocketDisconnect: (<CloseReason.GOING_AWAY: 1001>, '')                                                                                                              │
│ api-server Traceback (most recent call last):                                                                                                                                                          │
│ api-server   File "/app/ws/websocket_manager.py", line 24, in connect                                                                                                                                  │
│ api-server     message = await websocket.receive_text()                                                                                                                                                │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 119, in receive_text                                                                                         │
│ api-server     self._raise_on_disconnect(message)                                                                                                                                                      │
│ api-server   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 113, in _raise_on_disconnect                                                                                 │
│ api-server     raise WebSocketDisconnect(message["code"], message.get("reason"))                                                                                                                       │
│ api-server starlette.websockets.WebSocketDisconnect: (<CloseReason.NO_STATUS_RCVD: 1005>, '')     
```

Thanks for your help!

**Comment by davideserio** [comment]
With which image tag are you experiencing these errors? 0.2.0 or dev?

If you previously used dev images, in this case, add imagePullPolicy: Always

The keys VELERO_CLI_PATH_CUSTOM, VELERO_CLI_PATH, and VELERO_CLI_DEST_PATH have been removed since version 0.2.0.

**Comment by Llyr95** [comment]
It was with the dev image and I indeed previously used them. I have added imagePullPolicy: Always and that solved the issue

I confirm that the issue related to podVolumeBackup is solved. 

There is still the issue if I want to download the logs on the backup page : `HTTP 400 Bad Request: Error: 400: Error 408: Request Timeout 400: Invalid response: Content-Type application/octet-stream | File: service/logs.py | Function: get_backup_logs | Line: 38`

Also the dashboard is not loading : `Error
HTTP 400 Bad Request: Error: 'NoneType' object is not iterable | File: service/stats.py | Function: get_velero_stats | Line: 93`

Tell me if you want to move to another issue, technically the original issue is solved now ;)

**Comment by davideserio** [comment]
Hi,

Version 0.2.1 has been released, which fixes the issue with podVolumeBackup along with other minor bugs.
After updating, you should see the API and UI images at version 0.2.1.

If you are still experiencing errors related to logs and stats, please report them in a new issue, and I will investigate the problem further.
